In [1]:
import numpy as np

In [2]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [3]:
A

array([[ 5,  7,  9],
       [11,  6,  7],
       [11, 11,  7]])

In [4]:
B

array([[ 3, -1,  0],
       [-1,  1,  3],
       [ 1,  2,  3]])

In [5]:
# Поэлементное умножение
A*B

array([[ 15,  -7,   0],
       [-11,   6,  21],
       [ 11,  22,  21]])

In [6]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[17 20 48]
 [34  9 39]
 [29 14 54]]


In [7]:
# Матричное умножение
np.dot(A,B)

array([[17, 20, 48],
       [34,  9, 39],
       [29, 14, 54]])

In [8]:
# Матричное умножение
A@B

array([[17, 20, 48],
       [34,  9, 39],
       [29, 14, 54]])

In [9]:
# Порядок умножения AB != BA
B@A

array([[ 4, 15, 20],
       [39, 32, 19],
       [60, 52, 44]])

In [10]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 8  6  6  6  8]
 [ 9  7  7  7 11]
 [10 10  9  9  9]]
B:
 [[ 3  1]
 [ 0 -1]
 [-2  3]
 [-2 -2]
 [ 3  1]]


In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[24, 16],
       [32, 20],
       [21, 18]])

In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [ ]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

In [ ]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

In [ ]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

In [ ]:
b@A

In [ ]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

In [ ]:
# матрица Грама ортогональной системы векторов
A@A.T

In [ ]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

In [ ]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

In [ ]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)