Вызываем библиотеку numpy, т. к. именно в ней удобнее всего работать с векторами.

In [1]:
import numpy as np

Задаём вектор s→ как одномерный массив numpy с помощью функции np.array.

In [2]:
s = np.array([33, 65, 50, 45])
s
## array([33, 65, 50, 45])

array([33, 65, 50, 45])

Находим третью координату.

Помним, что в Python массивы нумеруются с нуля, а не с единицы, поэтому для третьей квартиры нужен элемент массива с номером 2.

In [3]:
s[2]
## 50

50

Находим размерность вектора. За размерность отвечает функция len().

In [4]:
len(s)
## 4

4

Сложение и вычитание векторов в Python происходит при помощи знаков + и -. Причём важно задать векторы именно как массивы numpy, а не как обычные списки типа list.

In [5]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
a + b
## array([15, 23, 14,  8])
a - b
## array([ 5, -7, -4, -6])

array([ 5, -7, -4, -6])

В Python число умножается на массив numpy обычным оператором умножения.

In [ ]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c
## array([24. ,  9. , 13.6])

Задание 2.5

Ниже представлены доходы семьи за три месяца.

Доходы мужа: 120, 150 и 190 тысяч рублей.
Доходы жены: 130, 130 и 130 тысяч рублей.
Доходы тёщи: 2, 3 и 2.5 тысячи евро.

In [11]:
w = np.array([120, 150, 190])
h = np.array([130, 130, 130])
m = np.array([2, 3, 2.5])
euro_rate = 72

m_rub = m*euro_rate

family = w+h+m_rub

display(m_rub)
display(family)

array([144., 216., 180.])

array([394., 496., 500.])

У риелтора Алексея есть канал в Telegram, где он формирует очередь на показы трёх особенно привлекательных квартир. Premium-показ стоит 500 рублей, VIP-показ — 100 рублей, обычный показ — бесплатно.

За неделю по каждой квартире было 2, 4 и 5 Premium-показов, 8, 10 и 2 VIP-показов и 0, 12 и 7 обычных показов соответственно.

Сколько Алексей заработал на показах по каждой квартире?

In [12]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u
## array([1800, 3000, 2700])

array([1800, 3000, 2700])

Найдите линейную комбинацию векторов x, y , u с коэффициентами 2, -3 и 5 соответственно.

In [14]:
x = np.array([4, 5])
y = np.array([2, 1])
u = np.array([1, 0])
a,b,c = 2,-3,5
lin_comb = a*x + b*y + c*u
lin_comb

array([7, 7])

Задание 2.8

Юный предприниматель Вовочка мастерит двигатели на водном топливе и продаёт их. За четыре недели он смастерил 3, 4, 5 и 9 двигателей, а продал 1, 5, 3 и 6 двигателей соответственно.

На изготовление одного двигателя Вовочка тратит 200 рублей, а продаёт двигатели по 400 рублейза штуку.

Найдите вектор прибыли (разницу между выручкой и затратами) Вовочки за эти четыре недели.

In [18]:
made = np.array([3, 4, 5, 9])
spend = np.array([1, 5, 3, 6])
cost = 200
price = 400
income = spend*price - made*cost
income

array([-200, 1200,  200,  600])

В Python скалярное произведение векторов вычисляется при помощи функции np.dot():

In [19]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)
## 102.0

102.0

In [21]:
a = np.array([4, 5, -1])
w = np.array([2, 0, 1])
np.dot(a, w)

7

В Hut_Paradise_DF представлен фрагмент базы данных агентства «Рай в Шалаше». По строкам расположены квартиры, по столбцам — параметры: арендная плата, общая площадь, количество комнат, этаж, количество показов на две недели и жилая площадь:

In [23]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

Задание 3.3

Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1).

In [27]:
A = Hut_Paradise_DF.values # возвращает значения df
print('Matrix:\n',A[4])

Matrix:
 [40 33  1  6 20 16]


Задание 3.4

Найдите вектор этажей всех квартир. Выберите координаты полученного вектора:

In [30]:
y=A[:,3] # 4 столбец матрицы А
print('floor vector:\n',y)

floor vector:
 [ 5 12 10  3  6 13  8 21  5]


Задание 3.5

Вычислите вектор нежилой площади. Выберите координаты полученного вектора:

In [32]:
la=A[:,5] # 6 столбец матрицы А
a=A[:,1] # 2 столбец матрицы А
print('no_liv.Area vector:\n',a-la)

liv.Area vector:
 [13 12 15 13 17  9 20 15 25]


Задание 3.6

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [34]:
demo_time=np.array([10,20,30,15,5,40,20,8,20])
demo_count=A[:,4]
display(demo_time@demo_count)

1348

Задание 3.7

Составьте линейную комбинацию векторов  v  и  w  с коэффициентами 2 и -3. Выберите координаты полученного вектора:

In [35]:
# Дано три вектора:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])
x=(2*v)+(-3*w)
x

array([-3, 14,  3,  4,  2])

Задание 3.8

Будет ли эта комбинация ортогональна вектору  u ?

In [37]:
y=x@u
display(y)

0