In [282]:
import numpy as np

Матрицу можно создать функцией np.matrix() или np.array(). Разницу между двумя этими способами мы обсудим в скринкасте.

За размер матрицы отвечает атрибут shape. 

In [283]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [284]:
A.shape
## (4, 3)
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])
## a_23= 1 a_32= 3 a_33= 1

a_23= 1 a_32= 3 a_33= 1


Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы numpy:

In [285]:
# import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

Задание 5.1

Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.

In [286]:
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income])
Inc=Inc.T

Задание 5.2

Составьте матрицу  Cons  расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.

In [287]:
Cons= np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption])
Cons=Cons.T

Задание 5.3

Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

Используйте полученную ранее матрицу Inc, где доходы расположены по столбцам.

In [288]:
inc_after_fi = Inc*0.87
inc_after_fi

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

Задание 5.4

Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

In [289]:
P = inc_after_fi-Cons
P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

В Python матрицы можно умножить с помощью функции np.dot(). При перемене мест сомножителей результат также меняется.

In [290]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")
display(A, B)

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [291]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [292]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

Задание 7.1

Даны матрица  A  и вектор  х :

Найдите произведение матрицы  A  и вектора  х  в том порядке, в котором их можно умножить.

In [293]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

A@x

array([26, 30])

Задание 7.2

Даны две матрицы: A & B

Найдите произведение матриц  A  и  B  в том порядке, в котором их можно умножить.

In [294]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

display(A, B)
B@A

array([[1, 9, 8, 5],
       [3, 6, 3, 2],
       [3, 3, 3, 3],
       [0, 2, 5, 9],
       [4, 4, 1, 2]])

array([[ 1, -1,  0,  1,  1],
       [-2,  0,  2, -1,  1]])

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

Задание 7.3

Составьте матрицу  A , расположив векторы  x ,  y ,  z  в строках. Найдите матрицу Грама  G  (матрицу скалярных произведений столбцов матрицы  A ) системы векторов  x ,  y ,  z.

Чему равна полученная матрица Грама  G ?

In [295]:
# Заданные векторы
x = np.array([1, 2, 1, 0, 4])
y = np.array([2, 1, -1, 1, 0])
z = np.array([-1, 1, -1, 0, 0])

# Составляем матрицу A, расположив векторы x, y, z в строках
A = np.array([x, y, z])

# Вычисляем матрицу Грама
G = A.T@A

# Выводим матрицу A и матрицу Грама G
print("Матрица A:")
print(A)
print("\nМатрица Грама G:")
print(G)


Матрица A:
[[ 1  2  1  0  4]
 [ 2  1 -1  1  0]
 [-1  1 -1  0  0]]

Матрица Грама G:
[[ 6  3  0  2  4]
 [ 3  6  0  1  8]
 [ 0  0  3 -1  4]
 [ 2  1 -1  1  0]
 [ 4  8  4  0 16]]


Условие для заданий 7.4 и 7.5

В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [296]:
import pandas as pd

Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)


Задание 7.4

Найдите вектор дохода салона по стилистам, если за каждую услугу стилисты платят салону определённую «комиссию».

Выберите координаты вектора прибыли салона:

In [298]:
# Вектор комиссий: 
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

revenue = Count_DF*Price_DF@com
np.array([revenue])

array([[11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25]])

Задание 7.5

Найдите вектор дохода стилистов.

In [299]:
income = Count_DF*Price_DF@(np.ones(5)-com)
np.array([income])

array([[ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75]])

Обратная матрица в Python вычисляется с помощью функции numpy.linalg.inv():

In [300]:
A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])

In [301]:
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

In [302]:
B = np.matrix('1,2; 2,5')
np.linalg.inv(B)

matrix([[ 5., -2.],
        [-2.,  1.]])

Вычисление определителя:

In [303]:
import numpy as np
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))
# -3.0000000000009

-2.9999999999999996


Давайте рассмотрим пример того, как вычислить ранг в Python. Для этого в библиотеке numpy существует специальная функция linalg.matrix_rank():

In [304]:
import numpy as np
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))
# 2

2


Задание 10.1

Дана матрица  A :

Найдите матрицу, обратную матрице  A .

In [305]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

A_inv=np.linalg.inv(A)
print('A inversed:\n',A_inv)

A inversed:
 [[-1.875    2.3125  -0.03125]
 [ 0.375   -0.5625   0.15625]
 [ 1.25    -1.375   -0.0625 ]]


In [306]:
# Условие для заданий 10.2-10.7
# Дана система векторов:

v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

Задание 10.2

Найдите ранг системы векторов  v1 ,  v2 ,  v3 ,  v4 . Для этого создайте матрицу системы векторов. Векторы в матрице расположите в столбцы.

In [311]:
M = np.array([v1, v2, v3, v4]).T
print(M)
print(np.linalg.matrix_rank(M))

[[ 9  2  4  3]
 [10  0  0 -4]
 [ 7  5  0  3]
 [ 7  1  4 -1]
 [ 9  4  1 -4]]
4


Задание 10.3

Является ли система векторов  v1 ,  v2 ,  v3 ,  v4  линейно зависимой?

Ранг матрицы  A , составленной из векторов  v1 ,  v2 ,  v3 ,  v4  равен 4, что равно количеству векторов в системе. Это значит, что система векторов является линейно независимой.

Задание 10.4

Найдите матрицу Грама системы векторов  v1 ,  v2 ,  v3 ,  v4 :  G=ATA . В качестве ответа запишите элемент из четвёртого столбца первой строки.

In [314]:
G=M.T@M
print('Матрица Грама:\n',G)

Матрица Грама:
 [[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]


Задание 10.5

Найдите определитель матрицы Грама  G  системы  v1 ,  v2 ,  v3 ,  v4 . 

Ответ округлите до целого числа.

In [317]:
print('Определитель матрицы Грама:\n',round(np.linalg.det(G),0))

Определитель матрицы Грама:
 3716648.0


Задание 10.6

Является ли матрица Грама системы  v1 ,  v2 ,  v3 ,  v4  вырожденной?

In [319]:
det_G = np.linalg.det(G)
print("\nДетерминант матрицы Грама:", det_G)

# Если детерминант матрицы Грама равен нулю, то матрица вырожденная. В противном случае она невырожденная.


Детерминант матрицы Грама: 3716647.9999999995


Задание 10.7

Найдите обратную матрицу к матрице Грама  G  системы  v1 ,  v2 ,  v3 ,  v4 .

In [320]:
print('Обратная к матрице Грама:\n',np.linalg.inv(G))

Обратная к матрице Грама:
 [[ 0.01711488 -0.02798543 -0.02623063  0.01599775]
 [-0.02798543  0.071967    0.03031441 -0.02722776]
 [-0.02623063  0.03031441  0.07683106 -0.02640498]
 [ 0.01599775 -0.02722776 -0.02640498  0.03479318]]
