## Задание 8.3

Попробуем применить градиентный спуск для решения реальной задачи линейной регрессии. Наша цель будет состоять в том, чтобы построить простую модель линейной регрессии для прогнозирования продаж некоторого продукта на основе количества денег, потраченных на рекламу.

Постройте модель, аналогичную той, что была разобрана в видео выше, но с тремя предикторами.

In [65]:
import numpy as np
import pandas as pd

In [66]:
df = pd.read_csv('Advertising.csv',index_col=0)

In [67]:
df.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [68]:
# Выбор нескольких столбцов с использованием двойных квадратных скобок
X = df[['TV', 'radio', 'newspaper']]
y = df['sales']
n = len(y)
# Добавление столбца единиц к X для учета смещения
X = np.append(np.ones((n,1)), X.values.reshape(n,3), axis = 1)
y = df['sales'].values.reshape(n,1)
par = np.zeros((4,1))

In [69]:
def cost_function(X, y , par):
    y_pred = np.dot(X, par)
    error = (y_pred - y)**2
    cost = 1/(n)*np.sum(error)
    return cost

In [70]:
def grad_d(X,y, par, alpha, iterations, eps=0.001):
    costs = []
    for i in range(iterations):
        y_pred = np.dot(X, par)
        der = np.dot (X.transpose(), (y_pred - y))/ n
        par -= alpha * der
        costs.append(cost_function(X,y, par))
        if np.linalg.norm(der) <= eps:
            break
    return par, costs

In [71]:
par, costs = grad_d(X,y, par, 0.00005, 500000)

In [75]:
display(par.round(3))
display(par[1].round(3))
display(par[2].round(3))
display(par[3].round(3))

array([[ 2.863e+00],
       [ 4.600e-02],
       [ 1.890e-01],
       [-1.000e-03]])

array([0.046])

array([0.189])

array([-0.001])

In [73]:
import numpy as np
import statsmodels.api as sm
mod = sm.OLS(y, X)
res = mod.fit()
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Mon, 10 Mar 2025   Prob (F-statistic):           1.58e-96
Time:                        09:28:32   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9389      0.312      9.422      0.0

In [74]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)
print(model.coef_)
print(model.intercept_)

[[ 0.          0.04576465  0.18853002 -0.00103749]]
[2.93888937]
