In [1]:
import numpy as np

7.2

In [1]:
import numpy as np
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)
elem_5_3 = mystery[4, 2]
last = mystery[-1, -1]
line_4 = mystery[3]
col_2 = mystery[:,-2]
part = mystery[1:4, 2:5]
rev = mystery[:, -1][::-1]
trans = mystery.transpose()

7.4

In [19]:
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)
nans_index = np.isnan(mystery)
n_nan = np.sum(nans_index)
mystery_new = mystery.copy()
mystery_new[np.isnan(mystery_new)] = 0
mystery_int = np.int32(mystery)
array = np.sort(mystery)
table = (array.reshape((3,5))).transpose()
col = table[:, 1]

[False False False  True False False False False  True False False False
  True False False]
15
[[ 12279. -26024.  28745.]
 [    nan  31244.  -2365.]
 [ -6974.  -9212.     nan]
 [-17722.  16132.  25933.]
 [    nan -16431.  29810.]]


C:\Users\Караваев\AppData\Local\Temp\ipykernel_16236\976375512.py:10: RuntimeWarning: invalid value encountered in cast
  mystery_int = np.int32(mystery)


In [21]:
import numpy as np

print(mystery2.min())
print(mystery2.mean())
print(np.median(mystery2))
print(round(np.std(mystery2), 2))

NameError: name 'mystery2' is not defined

In [22]:
import numpy as np
np.random.rand()

0.5976462445808154

In [24]:
np.random.rand(2, 3, 4, 10, 12, 23)

array([[[[[[6.86062979e-01, 5.27157995e-01, 9.55171820e-02, ...,
            1.66732679e-01, 7.64419393e-01, 5.72085219e-02],
           [2.05012403e-01, 2.34949990e-01, 1.27307011e-01, ...,
            1.22866912e-01, 6.77239109e-01, 2.21331952e-01],
           [7.70187199e-01, 2.12980353e-01, 1.38648189e-01, ...,
            5.81727109e-01, 9.35097713e-02, 8.53339467e-01],
           ...,
           [1.43274031e-01, 2.09924080e-02, 3.33292685e-01, ...,
            5.13086701e-01, 5.36948972e-02, 7.48668615e-01],
           [4.75394728e-01, 6.26337513e-01, 1.71155773e-01, ...,
            7.02365277e-01, 2.88478878e-01, 3.83314285e-01],
           [8.01811721e-01, 6.17039944e-01, 5.78132181e-01, ...,
            8.40311148e-01, 4.81836757e-01, 7.88926604e-01]],

          [[2.06772073e-01, 2.37600107e-01, 9.06345841e-01, ...,
            6.23124895e-01, 4.01911281e-01, 5.57118052e-01],
           [1.93754740e-01, 1.78995660e-01, 9.89826226e-01, ...,
            1.40870501e-02, 1.69111

In [26]:
np.random.seed(23)
np.random.randint(10, size=(3,4))
# array([[3, 6, 8, 9],
#        [6, 8, 7, 9],
#        [3, 6, 1, 2]])

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

9.6

In [50]:
import numpy as np
np.random.seed(2021)
simple = np.random.rand()
randoms = np.random.uniform(low=-150, high=2021, size=120)
table = np.random.randint(low=1, high=101, size=(3, 2))
even = np.arange(2, 17, 2)
print(even)
mix = even.copy()
print(mix)
mix = np.random.permutation(mix)
print(mix)
select = np.random.choice(even, size=3, replace=False)
triplet = np.random.permutation(select)


[ 2  4  6  8 10 12 14 16]
[ 2  4  6  8 10 12 14 16]
[ 6 10  2  8 14 16  4 12]


In [51]:
c=2**16
print(c)

65536


In [68]:
import numpy as np
def get_chess(a):
    tableron = np.zeros([a,a])
    tableron[1::2, ::2] = 1
    tableron[::2, 1::2] = 1
    return tableron

print(get_chess(a))


[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [78]:
import numpy as np
array = [1, 2, 3, 4, 5]
def shuffle_seed(array):
    our_seed = np.random.randint(2**32)
    # (low=0, high=(2**32), size = 1, dtype = np.uint32)
    np.random.seed(our_seed)
    shuffled_array = np.random.permutation(array)

    return (shuffled_array, our_seed)


print(shuffle_seed(array))

ValueError: high is out of bounds for int32

In [85]:
import numpy as np
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

vector_dists = list()
def min_max_dist(*vectors):
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            vector_dists.append(np.linalg.norm(vectors[i] - vectors[j]))

    return (min(vector_dists), max(vector_dists))

print(min_max_dist(vec1, vec2, vec3))

(5.196152422706632, 10.392304845413264)


10.8 hfccnjzybt vt;le dtrnjhfvb xthtp wbrkl d wbrkt

In [82]:
import numpy as np # импортируем библиотеку numpydef min_max_dist(*vectors):
# функция, которая принимает на вход неограниченное число векторов через запятую
    dists = list() # задаем пустой список
    for i in range(len(vectors)): # создаем в цикле список равный количеству векторов, это будут индексы-идентификаторы векторов
        for j in range(i + 1, len(vectors)): # в этом цикле тоже создаем индекс-идентификатор, но уже со сдвигом на 1, чтобы избежать повторений при расчете расстояний, так как расстояние между 1 вектором и 2 вектором = расстоянию между 2 и 1 и т.д.
            dists.append(np.linalg.norm(vectors[i] - vectors[j])) # добавляем в список  dists  вычисленную векторную норму (или расстояния между элементами в нашем наборе данных)
    return (min(dists), max(dists)) # возвращаем результат работы функции - минимальное и максимальное значение в списке dists в виде кортежа

IndentationError: unexpected indent (1433920873.py, line 3)

10.9 ищем паралельные векторы

In [89]:
import numpy as np
vectors_list = list()
def any_normal(*vectors):
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            if np.dot(vectors[i], vectors[j]) == 0:
                return True
    return False

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))

True


10.10

In [91]:
import numpy as np
def get_loto(num):
    loto_table = np.random.randint(1, 101, size=(num, 2,3))
    return loto_table

10.11

In [93]:
import numpy as np
def get_unique_loto(num):
    # создаем список чисел от 1 до 100
    sample = np.arange(1, 101)
    res = list()
    # цикл по каждому элементу в количестве num итераций
    for i in range(num):
        # в каждой итерации создаем массив 5на5 из случайно выбранных чисел из списка sample
        res.append(np.random.choice(sample, replace=False, size=(5, 5)))
    res = np.array(res)
    return res