In [110]:
import numpy as np
import pandas as pd

In [111]:
# Определим векторы как массивы NumPy
v1 = np.array([-1, 2, -7, 9])
v2 = np.array([2, 8, 2, -1])

# Найдем скалярное произведение векторов
p_1_2 = v1.T @ v2.T

print(p_1_2)


-9


Скалярное произведение векторов  v⃗   и  u⃗   равно 0. Что это значит с точки зрения геометрии?

Угол между векторами — 90 градусов, векторы ортогональны

Скалярное произведение векторов  v⃗   и  u⃗   равно 0. Что это значит с точки зрения их линейной (не)зависимости?

Векторы линейно независимы

In [112]:
# Найдите матрицу Грама.
A = np.matrix([[1, 1], [1, 2]])
A_G = A.T@A
print(A_G)

[[2 3]
 [3 5]]


In [113]:
# Проверим, что детерминант не равен нулю
det_A = np.linalg.det(A)
if det_A == 0:
    print("Матрица не имеет обратной, так как её детерминант равен нулю.")
else:
    # Вычислим обратную матрицу
    A_inv = np.linalg.inv(A)
    print("Обратная матрица:")
    print(A_inv)


Обратная матрица:
[[ 2. -1.]
 [-1.  1.]]


In [114]:
# Векторы
v1 = np.array([2, 10, -2])
v2 = np.array([3, 2, -2])
v3 = np.array([8, 14, -6])

# Составим матрицу из векторов
A = np.array([v1, v2, v3]).T

# Найдем ранг матрицы
rank = np.linalg.matrix_rank(A)

print("Ранг матрицы:", rank)


Ранг матрицы: 2


In [115]:
# Матрица A
A = np.array([
    [5, 1, 3],
    [0, 1, 8],
    [10, 0, 2]
])

# Вектор b
b = np.array([12, 10, 0])

# Расширенная матрица A|b
A_b = np.column_stack((A, b))

# Ранг матрицы A
rank_A = np.linalg.matrix_rank(A)

# Ранг расширенной матрицы A|b
rank_A_b = np.linalg.matrix_rank(A_b)

print("Ранг матрицы A:", rank_A)
print("Ранг расширенной матрицы A|b:", rank_A_b)

Ранг матрицы A: 3
Ранг расширенной матрицы A|b: 3


Задание 2.11

In [116]:
# Найдите матрицу Грама.
A = np.matrix([[1, 2], [-3, 1], [1, 2], [1, -1]])
A_G = A.T@A
print(A_G)


[[12  0]
 [ 0 10]]


In [117]:
# Проверим, что детерминант не равен нулю
det_A = np.linalg.det(A_G)
if det_A == 0:
    print("Матрица не имеет обратной, так как её детерминант равен нулю.")
else:
    # Вычислим обратную матрицу
    A_inv = np.linalg.inv(A_G)
    print("Обратная матрица:")
    print(A_inv)

Обратная матрица:
[[0.08333333 0.        ]
 [0.         0.1       ]]


In [118]:
# Вектор b
b = np.array([1, 4, 5, 0])
# Вычислим элементы вектора
b_el = A.T@b

In [119]:
# Нахождение вектора оценки 
w = np.linalg.inv(A.T@A)@A.T@b
w

matrix([[-0.5,  1.6]])

Задание 4.8

In [120]:
x1 = np.array([5.1, 1.8, 2.1, 10.3, 12.1, 12.6])
x2 = np.array([10.2, 3.7, 4.1, 20.5, 24.2, 24.1])
x3 = np.array([2.5, 0.9, 1.1, 5.1, 6.1, 6.3])
C = np.corrcoef([x1, x2, x3])
# Ранг матрицы A
rank_С = np.linalg.matrix_rank(C)
print("Ранг матрицы C:", rank_С)
print("Матрица C:")
print(C)

Ранг матрицы C: 3
Матрица C:
[[1.         0.99925473 0.99983661]
 [0.99925473 1.         0.99906626]
 [0.99983661 0.99906626 1.        ]]


In [121]:
# Вычисляем определитель матрицы C
det_C = np.linalg.det(C)
print('Determinant: {:.7f}'.format(det_C))


Determinant: 0.0000005
